#ifndef VEHICLE_H
#define VEHICLE_H

#include<string>

using namespace std;

class Vehicle
{
    public:
        Vehicle();
        Vehicle(unsigned int, string, string);
        virtual ~Vehicle();
        //Autogenerated
        unsigned int GetyearBuilt() { return yearBuilt; }
        void SetyearBuilt(unsigned int val) { yearBuilt = val; }
        string Getmanufaturer() { return manufaturer; }
        void Setmanufaturer(string val) { manufaturer = val; }

        string Getmodal(){ return modal; }
        void Setmodal(string val){ modal = val; }
        void displayInfo() const; // mayhaps should be virtual

    protected:

    private:
        unsigned int yearBuilt;
        string manufaturer;
        string modal; // I have a brother who talks about vehicles too frequently for me to be able to only use two pieces of information.
};

#endif // VEHICLE_H
